# 🧹 Module 2: Data Cleaning

## 🎯 Objective
Now that you’ve explored the dataset and identified issues, it’s time to clean the data so that we can use it for analysis.

You will:
- Convert data types (e.g., Date, Quantity, Price)
- Handle missing and invalid values
- Remove duplicates
- Standardize categorical variables

Your cleaned dataset will be the foundation for calculating portfolio value in the next module.

### Step 2.0 – Import the DataFrame

Make sure you start from the same dataset you explored in Module 1.

Import the CSV File

In [12]:
# 💡 Tip: Use the csv format
# YOUR CODE HERE
import pandas as pd
df = pd.read_csv("Data_To_Clean")
df.head()

   Asset  Quantity       Price        Date      Type
0   MSFT      62.0     1368.49  2024-12-13       Buy
1   AMZN      20.5  4968573.82   yesterday       123
2  GOOGL      20.5  5147465.61         NaN  Purchase
3  GOOGL      15.0      994.09  2024-10-05       Buy
4    NaN       NaN         NaN  2023-15-01      Sell

### Step 2.1 – Convert data types

Make sure:
- `Date` is a datetime object
- `Quantity` and `Price` are numeric

If conversion fails due to bad data, handle errors gracefully (e.g., use `errors='coerce'`).

In [13]:
# 💡 Tip: Use pd.to_datetime() and pd.to_numeric()
# Convert Date column
df["Date"] = pd.to_datetime(df["Date"], errors='coerce')
# YOUR CODE HERE
# Convert Quantity and Price
df["Quantity"] = pd.to_numeric(df["Quantity"], errors='coerce')
df["Price"] = pd.to_numeric(df["Price"], errors='coerce')
# YOUR CODE HERE

### Step 2.2 – Remove invalid or missing rows

Decide how to deal with rows that:
- Have missing `Asset`, `Quantity`, or `Price`
- Have `Quantity` or `Price` <= 0
- Have a missing or invalid `Date`

Hint: Not all missing values should be dropped blindly. You may want to drop only critical columns.

Clean based on what would break portfolio valuation.

In [14]:
# 💡 Tip: Use .dropna() and boolean filtering

# Remove rows with missing or invalid critical fields
df = df.dropna()
df

# YOUR CODE HERE

    Asset  Quantity    Price       Date  Type
0    MSFT      62.0  1368.49 2024-12-13   Buy
3   GOOGL      15.0   994.09 2024-10-05   Buy
7   GOOGL      22.0  1255.17 2024-08-24   Buy
11   TSLA      34.0   932.06 2024-09-21  Sell
12   TSLA      14.0   853.56 2024-11-13  Sell
14  GOOGL      91.0   781.76 2024-09-09   Buy
19   MSFT       9.0  1291.22 2025-02-21   Buy
22   MSFT      53.0   459.17 2024-12-24  Sell
23   AMZN      51.0   254.40 2025-02-18  Sell
28   MSFT      29.0  1139.11 2024-08-09   Buy

### Step 2.3 – Keep only valid trade types

Valid trade types are: `'Buy'` and `'Sell'`

All others (e.g. `Hold`, empty string, NaN) should be removed or fixed.

In [15]:
# 💡 Tip: Use .isin() to filter only valid values

# Filter the 'Type' column
# YOUR CODE HERE
Valid_Types = ["Buy", "Sell"]
df = df[df["Type"].isin(Valid_Types)]
df

    Asset  Quantity    Price       Date  Type
0    MSFT      62.0  1368.49 2024-12-13   Buy
3   GOOGL      15.0   994.09 2024-10-05   Buy
7   GOOGL      22.0  1255.17 2024-08-24   Buy
11   TSLA      34.0   932.06 2024-09-21  Sell
12   TSLA      14.0   853.56 2024-11-13  Sell
14  GOOGL      91.0   781.76 2024-09-09   Buy
19   MSFT       9.0  1291.22 2025-02-21   Buy
22   MSFT      53.0   459.17 2024-12-24  Sell
23   AMZN      51.0   254.40 2025-02-18  Sell
28   MSFT      29.0  1139.11 2024-08-09   Buy

### Step 2.4 – Standardize text columns

Some entries in the `Asset` or `Type` columns might be lowercase or contain whitespace.

Clean them by:
- Removing extra spaces
- Making everything uppercase (or consistent case)
- Dropping empty strings if necessary

In [16]:
# 💡 Tip: Use .str.strip() and .str.upper()

# Clean Asset column
# YOUR CODE HERE
df['Asset'] = df['Asset'].str.strip().str.upper()
# Clean Type column
df['Type'] = df['Type'].str.strip().str.upper()
# YOUR CODE HERE
df

    Asset  Quantity    Price       Date  Type
0    MSFT      62.0  1368.49 2024-12-13   BUY
3   GOOGL      15.0   994.09 2024-10-05   BUY
7   GOOGL      22.0  1255.17 2024-08-24   BUY
11   TSLA      34.0   932.06 2024-09-21  SELL
12   TSLA      14.0   853.56 2024-11-13  SELL
14  GOOGL      91.0   781.76 2024-09-09   BUY
19   MSFT       9.0  1291.22 2025-02-21   BUY
22   MSFT      53.0   459.17 2024-12-24  SELL
23   AMZN      51.0   254.40 2025-02-18  SELL
28   MSFT      29.0  1139.11 2024-08-09   BUY

### Step 2.5 – Remove duplicates

If there are duplicate trades, remove them to avoid double-counting in future portfolio valuation.

In [17]:
# 💡 Tip: Use .drop_duplicates()
df = df.drop_duplicates()
df
# YOUR CODE HERE

    Asset  Quantity    Price       Date  Type
0    MSFT      62.0  1368.49 2024-12-13   BUY
3   GOOGL      15.0   994.09 2024-10-05   BUY
7   GOOGL      22.0  1255.17 2024-08-24   BUY
11   TSLA      34.0   932.06 2024-09-21  SELL
12   TSLA      14.0   853.56 2024-11-13  SELL
14  GOOGL      91.0   781.76 2024-09-09   BUY
19   MSFT       9.0  1291.22 2025-02-21   BUY
22   MSFT      53.0   459.17 2024-12-24  SELL
23   AMZN      51.0   254.40 2025-02-18  SELL
28   MSFT      29.0  1139.11 2024-08-09   BUY

### Step 2.6 – Reset the DataFrame index

After all rows have been removed or filtered, reset the index to keep the dataset clean and sequential.

In [18]:
# 💡 Tip: Use .reset_index(drop=True)
df.reset_index(drop=True)
# YOUR CODE HERE

   Asset  Quantity    Price       Date  Type
0   MSFT      62.0  1368.49 2024-12-13   BUY
1  GOOGL      15.0   994.09 2024-10-05   BUY
2  GOOGL      22.0  1255.17 2024-08-24   BUY
3   TSLA      34.0   932.06 2024-09-21  SELL
4   TSLA      14.0   853.56 2024-11-13  SELL
5  GOOGL      91.0   781.76 2024-09-09   BUY
6   MSFT       9.0  1291.22 2025-02-21   BUY
7   MSFT      53.0   459.17 2024-12-24  SELL
8   AMZN      51.0   254.40 2025-02-18  SELL
9   MSFT      29.0  1139.11 2024-08-09   BUY

In [19]:
# Make Quantity negative for SELL trades
df.loc[df['Type'] == 'SELL', 'Quantity'] *= -1
df

    Asset  Quantity    Price       Date  Type
0    MSFT      62.0  1368.49 2024-12-13   BUY
3   GOOGL      15.0   994.09 2024-10-05   BUY
7   GOOGL      22.0  1255.17 2024-08-24   BUY
11   TSLA     -34.0   932.06 2024-09-21  SELL
12   TSLA     -14.0   853.56 2024-11-13  SELL
14  GOOGL      91.0   781.76 2024-09-09   BUY
19   MSFT       9.0  1291.22 2025-02-21   BUY
22   MSFT     -53.0   459.17 2024-12-24  SELL
23   AMZN     -51.0   254.40 2025-02-18  SELL
28   MSFT      29.0  1139.11 2024-08-09   BUY

In [20]:
df.drop(columns=["Type"], inplace=True)
df

    Asset  Quantity    Price       Date
0    MSFT      62.0  1368.49 2024-12-13
3   GOOGL      15.0   994.09 2024-10-05
7   GOOGL      22.0  1255.17 2024-08-24
11   TSLA     -34.0   932.06 2024-09-21
12   TSLA     -14.0   853.56 2024-11-13
14  GOOGL      91.0   781.76 2024-09-09
19   MSFT       9.0  1291.22 2025-02-21
22   MSFT     -53.0   459.17 2024-12-24
23   AMZN     -51.0   254.40 2025-02-18
28   MSFT      29.0  1139.11 2024-08-09

### ✅ Final Check: Review the cleaned dataset

Display the first few rows and check:
- Are there still any NaNs?
- Are all values consistent and valid?

In [21]:
# 💡 Tip: Use .head() and .isnull().sum()
df.head().isnull().sum()
# YOUR CODE HERE

Asset       0
Quantity    0
Price       0
Date        0
dtype: int64

## 📦 Save the cleaned DataFrame

You’ll need this cleaned dataset for the next module (portfolio computation). Let’s save it into a new variable.

In [22]:
# 💡 Tip: Use a meaningful name like df_clean
df.to_csv('Clean_Data', index=False)
# YOUR CODE HERE